"""Register FMB assembly objects in the global NAME_TO_OBJECT registry.

Mirrors fabrica/objects.py but scans assets/urdf/fmb/ for assemblies.
Auto-discovers any subdirectory containing canonical_transforms.json.

Also registers individual long pegs from assets/urdf/fmb/pegs/peg_X/ (used
by the peg-in-hole-board problems). Each peg_X dir is expected to contain
peg_X_canonical.obj + peg_X.urdf + coacd/peg_X_coacd.urdf, generated by
peg_in_hole_dynamic.fmb.peg_board_problem_setup.step2_generate_assets.
"""

import json
from pathlib import Path

import trimesh

from dextoolbench.objects import Object, rescale_by_factor, NAME_TO_OBJECT
from isaacgymenvs.utils.utils import get_repo_root_dir

ASSETS_DIR = get_repo_root_dir() / "assets" / "urdf" / "fmb"


def _discover_assemblies():
    if not ASSETS_DIR.exists():
        return []
    return sorted(
        d.name
        for d in ASSETS_DIR.iterdir()
        if d.is_dir() and (d / "canonical_transforms.json").exists()
    )


ALL_FMB_ASSEMBLIES = _discover_assemblies()


def _load_assembly_objects(assembly_name):
    transforms_path = ASSETS_DIR / assembly_name / "canonical_transforms.json"
    if not transforms_path.exists():
        return {}

    with open(transforms_path) as f:
        transforms = json.load(f)

    objects = {}
    for pid, data in transforms.items():
        name = f"{assembly_name}_{pid}"
        part_dir = ASSETS_DIR / assembly_name / pid
        ext = data["canonical_extents"]
        scale = rescale_by_factor(tuple(ext), factor=25)

        urdf_path = part_dir / f"{name}.urdf"
        if urdf_path.exists():
            objects[name] = Object(urdf_path=urdf_path, scale=scale, need_vhacd=True)

        sdf_urdf_path = part_dir / f"{name}_sdf.urdf"
        if sdf_urdf_path.exists():
            objects[f"{name}_sdf"] = Object(urdf_path=sdf_urdf_path, scale=scale, need_vhacd=False)

        coacd_urdf_path = part_dir / "coacd" / f"{name}_coacd.urdf"
        if coacd_urdf_path.exists():
            objects[f"{name}_coacd"] = Object(urdf_path=coacd_urdf_path, scale=scale, need_vhacd=False)

    return objects


def _load_long_peg_objects():
    """Register peg_X long-peg objects from assets/urdf/fmb/pegs/.

    Each peg_X dir must have a canonical mesh + visual URDF + CoACD URDF
    generated by step2_generate_assets. Pegs without all three are skipped.
    """
    pegs_root = ASSETS_DIR / "pegs"
    if not pegs_root.is_dir():
        return {}
    objects = {}
    for peg_dir in sorted(pegs_root.iterdir()):
        if not peg_dir.is_dir():
            continue
        name = peg_dir.name                             # e.g. "peg_31"
        canonical_obj = peg_dir / f"{name}_canonical.obj"
        urdf_path     = peg_dir / f"{name}.urdf"
        coacd_urdf    = peg_dir / "coacd" / f"{name}_coacd.urdf"
        if not (canonical_obj.is_file() and urdf_path.is_file() and coacd_urdf.is_file()):
            continue
        m = trimesh.load_mesh(str(canonical_obj), process=False)
        scale = rescale_by_factor(tuple(m.extents.tolist()), factor=25)
        objects[f"fmb_{name}"]       = Object(urdf_path=urdf_path,  scale=scale, need_vhacd=False)
        objects[f"fmb_{name}_coacd"] = Object(urdf_path=coacd_urdf, scale=scale, need_vhacd=False)

        # Optional SDF + CoACD hybrid variant generated by
        # step3_generate_sdf_hybrid.py. need_vhacd=False is critical —
        # V-HACD on the multi-link URDF would re-decompose both the SDF
        # mesh and the body CoACD hulls, breaking both.
        sdf_hybrid_urdf = peg_dir / "sdf_hybrid" / f"{name}_sdf_hybrid.urdf"
        if sdf_hybrid_urdf.is_file():
            objects[f"fmb_{name}_sdf_hybrid"] = Object(
                urdf_path=sdf_hybrid_urdf, scale=scale, need_vhacd=False,
            )
    return objects


FMB_NAME_TO_OBJECT = {}
for _assembly in ALL_FMB_ASSEMBLIES:
    FMB_NAME_TO_OBJECT.update(_load_assembly_objects(_assembly))
FMB_NAME_TO_OBJECT.update(_load_long_peg_objects())

NAME_TO_OBJECT.update(FMB_NAME_TO_OBJECT)
