#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_DIR}"

RUN_TIMESTAMP="$(date +%F_%H-%M-%S)"

export OUT_DIR="${OUT_DIR:-local_logs/${RUN_TIMESTAMP}_simtoolreal_ref_pan_refined_crisper_objectpop_20s}"
export MAKE_VIDEO="${MAKE_VIDEO:-1}"
export STEPS="${STEPS:-1200}"
export CAPTURE_PNG_STEPS="${CAPTURE_PNG_STEPS:-0,300,600,900,1200}"

export BACKDROP_GRADIENT_BANDS="${BACKDROP_GRADIENT_BANDS:-32}"
export FLOOR_STYLE="${FLOOR_STYLE:-soft_concrete_pbr_tiles}"
export FLOOR_COLOR_R="${FLOOR_COLOR_R:-0.56}"
export FLOOR_COLOR_G="${FLOOR_COLOR_G:-0.56}"
export FLOOR_COLOR_B="${FLOOR_COLOR_B:-0.53}"
export FLOOR_TILE_COUNT="${FLOOR_TILE_COUNT:-1}"
export FLOOR_TILE_SIZE="${FLOOR_TILE_SIZE:-120}"
export FLOOR_TILE_GAP="${FLOOR_TILE_GAP:-0}"
export FLOOR_TEXTURE_SCALE="${FLOOR_TEXTURE_SCALE:-8.0}"
export FLOOR_ROUGHNESS="${FLOOR_ROUGHNESS:-0.92}"
export FLOOR_NORMAL_STRENGTH="${FLOOR_NORMAL_STRENGTH:-0.05}"
export FLOOR_SPECULAR_LEVEL="${FLOOR_SPECULAR_LEVEL:-0.04}"

export TABLE_COLOR_R="${TABLE_COLOR_R:-0.40}"
export TABLE_COLOR_G="${TABLE_COLOR_G:-0.30}"
export TABLE_COLOR_B="${TABLE_COLOR_B:-0.22}"

export BACKDROP_COLOR_R="${BACKDROP_COLOR_R:-0.24}"
export BACKDROP_COLOR_G="${BACKDROP_COLOR_G:-0.46}"
export BACKDROP_COLOR_B="${BACKDROP_COLOR_B:-0.75}"
export BACKDROP_HORIZON_COLOR_R="${BACKDROP_HORIZON_COLOR_R:-0.60}"
export BACKDROP_HORIZON_COLOR_G="${BACKDROP_HORIZON_COLOR_G:-0.72}"
export BACKDROP_HORIZON_COLOR_B="${BACKDROP_HORIZON_COLOR_B:-0.84}"

export OBJECT_COLOR_SATURATION="${OBJECT_COLOR_SATURATION:-1.75}"
export OBJECT_COLOR_VALUE_SCALE="${OBJECT_COLOR_VALUE_SCALE:-0.88}"

export SINGLE_SUN_ELEVATION_DEG="${SINGLE_SUN_ELEVATION_DEG:-48}"
export SINGLE_SUN_EXPOSURE="${SINGLE_SUN_EXPOSURE:-9.62}"
export SINGLE_SUN_ANGLE="${SINGLE_SUN_ANGLE:-0.24}"
export SINGLE_SUN_COLOR_TEMPERATURE="${SINGLE_SUN_COLOR_TEMPERATURE:-5150}"
export SINGLE_SUN_COLOR_R="${SINGLE_SUN_COLOR_R:-1.00}"
export SINGLE_SUN_COLOR_G="${SINGLE_SUN_COLOR_G:-0.965}"
export SINGLE_SUN_COLOR_B="${SINGLE_SUN_COLOR_B:-0.87}"
export SINGLE_SUN_YAW_OFFSET_DEG="${SINGLE_SUN_YAW_OFFSET_DEG:-105}"
export DEFAULT_LIGHT_INTENSITY="${DEFAULT_LIGHT_INTENSITY:-390}"
export SKY_DOME_INTENSITY="${SKY_DOME_INTENSITY:-1260}"

export IMAGE_EXPOSURE="${IMAGE_EXPOSURE:--0.20}"
export IMAGE_CONTRAST="${IMAGE_CONTRAST:-1.08}"
export IMAGE_SATURATION="${IMAGE_SATURATION:-1.06}"
export IMAGE_GAMMA="${IMAGE_GAMMA:-0.98}"

exec bash_scripts/98_render_simtoolreal_ref_pan_cinematic_greige_floor.sh "$@"
