import json
from pathlib import Path

from dextoolbench.objects import Object, rescale_by_factor, NAME_TO_OBJECT

from isaacgymenvs.utils.utils import get_repo_root_dir

ASSETS_DIR = get_repo_root_dir() / "assets" / "urdf" / "fabrica"

ALL_ASSEMBLIES = [
    "beam",
    "car",
    "cooling_manifold",
    "duct",
    "gamepad",
    "plumbers_block",
    "stool_circular",
]

CANONICAL_URDF_TEMPLATE = """\
<?xml version="1.0"?>
<robot name="{name}">
  <link name="{name}">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="{mesh_file}" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="{mesh_file}" scale="1 1 1"/>
      </geometry>
    </collision>
    <inertial>
      <density value="1250.0"/>
    </inertial>
  </link>
</robot>
"""

SDF_URDF_TEMPLATE = """\
<?xml version="1.0"?>
<robot name="{name}">
  <link name="{name}">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="{mesh_file}" scale="1 1 1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="{mesh_file}" scale="1 1 1"/>
      </geometry>
      <sdf resolution="{sdf_resolution}"/>
    </collision>
    <inertial>
      <density value="1250.0"/>
    </inertial>
  </link>
</robot>
"""

DEFAULT_SDF_RESOLUTION = 512


def _load_assembly_objects(assembly_name):
    """Load Object entries using canonical extents from canonical_transforms.json.

    Also creates canonical URDFs if they don't exist.
    """
    transforms_path = ASSETS_DIR / assembly_name / "canonical_transforms.json"
    if not transforms_path.exists():
        return {}

    with open(transforms_path) as f:
        transforms = json.load(f)

    objects = {}
    for pid, data in transforms.items():
        name = f"{assembly_name}_{pid}"
        part_dir = ASSETS_DIR / assembly_name / pid
        canonical_obj = part_dir / f"{pid}_canonical.obj"
        urdf_path = part_dir / f"{name}.urdf"

        # Ensure URDF references canonical mesh
        if canonical_obj.exists():
            expected = CANONICAL_URDF_TEMPLATE.format(
                name=name,
                mesh_file=f"{pid}_canonical.obj",
            )
            if not urdf_path.exists() or urdf_path.read_text() != expected:
                urdf_path.write_text(expected)

        ext = data["canonical_extents"]
        objects[name] = Object(
            urdf_path=urdf_path,
            scale=rescale_by_factor(tuple(ext), factor=25),
            need_vhacd=True,
        )

        # SDF variant: same mesh but with SDF collision instead of V-HACD
        sdf_name = f"{name}_sdf"
        sdf_urdf_path = part_dir / f"{sdf_name}.urdf"
        if canonical_obj.exists():
            sdf_expected = SDF_URDF_TEMPLATE.format(
                name=sdf_name,
                mesh_file=f"{pid}_canonical.obj",
                sdf_resolution=DEFAULT_SDF_RESOLUTION,
            )
            if not sdf_urdf_path.exists() or sdf_urdf_path.read_text() != sdf_expected:
                sdf_urdf_path.write_text(sdf_expected)

        objects[sdf_name] = Object(
            urdf_path=sdf_urdf_path,
            scale=rescale_by_factor(tuple(ext), factor=25),
            need_vhacd=False,
        )

        # CoACD variant: pre-decomposed convex hulls (generated by run_coacd.py)
        coacd_name = f"{name}_coacd"
        coacd_urdf_path = part_dir / "coacd" / f"{coacd_name}.urdf"
        if coacd_urdf_path.exists():
            objects[coacd_name] = Object(
                urdf_path=coacd_urdf_path,
                scale=rescale_by_factor(tuple(ext), factor=25),
                need_vhacd=False,
            )

    return objects


FABRICA_NAME_TO_OBJECT = {}
for _assembly in ALL_ASSEMBLIES:
    FABRICA_NAME_TO_OBJECT.update(_load_assembly_objects(_assembly))

# Register into the global object registry so the sim can find them
NAME_TO_OBJECT.update(FABRICA_NAME_TO_OBJECT)
