import json
from pathlib import Path

from dextoolbench.objects import Object, rescale_by_factor, NAME_TO_OBJECT

from isaacgymenvs.utils.utils import get_repo_root_dir

ASSETS_DIR = get_repo_root_dir() / "assets" / "urdf" / "fabrica"

ALL_ASSEMBLIES = [
    "beam",
    "car",
    "cooling_manifold",
    "duct",
    "gamepad",
    "plumbers_block",
    "stool_circular",
]

def _load_assembly_objects(assembly_name):
    """Load Object entries using canonical extents from canonical_transforms.json.

    URDFs are expected to already exist (generated by compute_canonical.py
    and run_coacd.py). This function only reads, never writes.
    """
    transforms_path = ASSETS_DIR / assembly_name / "canonical_transforms.json"
    if not transforms_path.exists():
        return {}

    with open(transforms_path) as f:
        transforms = json.load(f)

    objects = {}
    for pid, data in transforms.items():
        name = f"{assembly_name}_{pid}"
        part_dir = ASSETS_DIR / assembly_name / pid
        ext = data["canonical_extents"]
        scale = rescale_by_factor(tuple(ext), factor=25)

        # Base variant (V-HACD collision)
        urdf_path = part_dir / f"{name}.urdf"
        if urdf_path.exists():
            objects[name] = Object(urdf_path=urdf_path, scale=scale, need_vhacd=True)

        # SDF variant
        sdf_urdf_path = part_dir / f"{name}_sdf.urdf"
        if sdf_urdf_path.exists():
            objects[f"{name}_sdf"] = Object(urdf_path=sdf_urdf_path, scale=scale, need_vhacd=False)

        # CoACD variant (generated by run_coacd.py)
        coacd_urdf_path = part_dir / "coacd" / f"{name}_coacd.urdf"
        if coacd_urdf_path.exists():
            objects[f"{name}_coacd"] = Object(urdf_path=coacd_urdf_path, scale=scale, need_vhacd=False)

    return objects


FABRICA_NAME_TO_OBJECT = {}
for _assembly in ALL_ASSEMBLIES:
    FABRICA_NAME_TO_OBJECT.update(_load_assembly_objects(_assembly))

# Register into the global object registry so the sim can find them
NAME_TO_OBJECT.update(FABRICA_NAME_TO_OBJECT)

# Chain-register sibling benchmarks. Importing these here guarantees that any
# code path which imports fabrica.objects (including FabricaEnv construction)
# also picks up their NAME_TO_OBJECT entries.
try:
    import peg_in_hole.objects  # noqa: F401
except ImportError:
    pass
