num_episodes: 20
max_steps: 700
action_loss_weight: 1.0
aux_object_pos_weight: 1.0
hand_moving_average: 0.1
arm_moving_average: 0.1
dof_speed_scale: 1.5
control_dt: 0.016666666666666666
checkpoint_interval: 1
image_height: 180
image_width: 320
learning_rate: 0.0001
num_envs: 4096
env_spacing: 4.0
object_start_mode: fixed
object_pos_noise_xyz: [0.0, 0.0, 0.0]
object_yaw_noise_deg: 0.0
