num_episodes: 1
max_steps: 700
action_loss_weight: 1.0
aux_object_pos_weight: 1.0
hand_moving_average: 0.1
arm_moving_average: 0.1
dof_speed_scale: 1.5
control_dt: 0.016666666666666666
beta_mode: always_student
beta_start: 0.0
beta_end: 0.0
beta_decay: 0.0
beta_metric_threshold: 0.8
beta_update_episodes: 2
beta_hold_episodes: 0
checkpoint_interval: 10
eval_interval: 999
eval_num_envs: 0
eval_max_steps: 700
image_height: 45
image_width: 80
learning_rate: 0.0001
num_envs: 512
env_spacing: 4.0
object_start_mode: randomized
object_pos_noise_xyz: [0.015, 0.015, 0.005]
object_yaw_noise_deg: 8.0
monitor_num_envs: 0
monitor_log_window: 10
camera_backend: tiled
depth_preprocess_mode: clip_divide
depth_min_m: 0.0
depth_max_m: 5.0
episode_length: 600
reset_when_dropped: false
online_num_iters: 350000
online_log_interval: 1000
online_update_interval: 1
image_robustness:
  enabled: true
  visual_dr:
    enabled: true
    camera_pos_jitter_m: [0.03, 0.03, 0.03]
    camera_rot_jitter_deg: [3.0, 3.0, 3.0]
    dome_light_randomization: true
    dome_light_intensity_range: [1500.0, 4000.0]
    dome_light_color_jitter: 0.25
    material_color_randomization: true
  rgb_aug:
    enabled: true
    background_prob: 0.5
    color_jitter_prob: 1.0
    motion_blur_prob: 0.1
    saturation_range: [0.5, 1.5]
    contrast_range: [0.5, 1.5]
    brightness_range: [0.5, 1.5]
    hue_range: [-0.15, 0.15]
    motion_blur_kernel_sizes: [9, 11, 13, 15, 17]
  depth_aug:
    enabled: false
  image_delay:
    enabled: true
    max_random_delay_frames: 2
    resample_on_reset: true
  preprocess:
    resize_mode: exact
    pad_to_size: false
    apply_rgb_float_scaling: true
    zero_out_invalid_depth: true
