wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: performance/elapsed_minutes
      6:
      - 3
    - 1: performance/frames_vs_minutes
      5: 1
      6:
      - 1
      - 3
    python_version: 3.8.20
    start_time: 1772064989
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 7
      - 13
      - 16
      - 35
      4: 3.8.20
      5: 0.12.21
      8:
      - 5
capture_video:
  desc: null
  value: false
capture_video_freq:
  desc: null
  value: 1464
capture_video_len:
  desc: null
  value: 100
checkpoint:
  desc: null
  value: ''
checkpoint_yaml:
  desc: null
  value: ''
experiment:
  desc: null
  value: 00_depth_2gpu_test
force_render:
  desc: null
  value: true
graphics_device_id:
  desc: null
  value: 0
headless:
  desc: null
  value: true
max_iterations:
  desc: null
  value: ''
multi_gpu:
  desc: null
  value: true
num_envs:
  desc: null
  value: ''
num_subscenes:
  desc: null
  value: 4
num_threads:
  desc: null
  value: 4
pbt:
  desc: null
  value:
    enabled: false
physics_engine:
  desc: null
  value: physx
pipeline:
  desc: null
  value: gpu
rl_device:
  desc: null
  value: cuda:0
seed:
  desc: null
  value: 0
sigma:
  desc: null
  value: ''
sim_device:
  desc: null
  value: cuda:0
solver_type:
  desc: null
  value: 1
task:
  desc: null
  value:
    env:
      VISUALIZE_PD_TARGET_AS_BLUE_ROBOT: false
      actionDelayMax: 3
      add_prev_targets_to_obs: false
      angVelImpulseOnlyWhenLifted: true
      angVelImpulseProbRange:
      - 0.001
      - 0.1
      angVelImpulseScale: 0.0
      armMovingAverage: 0.1
      armMovingAverageFinal: null
      asset:
        robot: urdf/kuka_sharpa_description/iiwa14_left_sharpa_adjusted_restricted.urdf
        table: urdf/table_narrow.urdf
      capture_video: true
      capture_video_freq: 6000
      capture_video_len: 600
      clampAbsObservations: 10.0
      controlFrequencyInv: 1
      curriculumSuccessRatio: 0.6
      deltaGoalDistance: 0.1
      deltaRotationDegrees: 90.0
      depthCamera:
        enabled: true
        encoderLearningRate: 1.0e-05
        encoderType: scratch_cnn
        farPlane: 1.5
        featureDim: 512
        freezeEncoder: false
        height: 64
        horizontalFov: 70.0
        localPos:
        - 0.0
        - 0.04
        - 0.0
        localRot:
        - 0.0
        - 0.0
        - 0.0
        - 1.0
        mountLink: iiwa14_link_6
        nearPlane: 0.01
        unfreezeAfterEpochs: -1
        width: 64
      distanceDeltaRewScale: 50.0
      dofSpeedScale: 10
      dofSpeedScaleFinal: null
      enableCameraSensors: true
      enableDebugVis: false
      envSpacing: 1.2
      episodeLength: 600
      evalStats: false
      evalSuccessTolerance: null
      fallDistance: 0.24
      fallPenalty: 0.0
      fingerTipFriction: 1.5
      fixedGoalStates: null
      fixedGoalStatesJsonPath: null
      fixedSize:
      - 0.141
      - 0.03025
      - 0.0271
      fixedSizeKeypointReward: true
      forceConsecutiveNearGoalSteps: true
      forceDecay: 0.0
      forceDecayInterval: 0.08
      forceLimitScale: 1.0
      forceNoReset: false
      forceOnlyWhenLifted: true
      forceProbRange:
      - 0.001
      - 0.1
      forceScale: 20
      goalObjectPose: null
      goalSamplingType: delta
      goodResetBoundary: 0
      hack_object_pos_offset: 0.05
      handActionsPenaltyScale: 0.003
      handMovingAverage: 0.1
      handMovingAverageFinal: null
      handleHeadTypes:
      - hammer
      - screwdriver
      - marker
      - spatula
      - eraser
      - brush
      init_tyler_curriculum_scale: 0.0
      jointAccelerationPenaltyScale: 0.0
      jointVelocityObsNoiseStd: 0.1
      jointVelocityPenaltyScale: 0.0
      keypointRewScale: 200.0
      keypointScale: 1.5
      kukaActionsPenaltyScale: 0.03
      liftingBonus: 300.0
      liftingBonusThreshold: 0.15
      liftingRewScale: 20.0
      linVelImpulseOnlyWhenLifted: true
      linVelImpulseProbRange:
      - 0.001
      - 0.1
      linVelImpulseScale: 0.0
      loadInitialStates: false
      loadStatesFile: rootTensorsDofStates.bin
      maxConsecutiveSuccesses: 50
      modifyAssetFrictions: true
      numEnvs: 512
      objectAngVelPenaltyScale: 0.0
      objectBaseSize: 0.04
      objectFriction: 0.5
      objectLinVelPenaltyScale: 0.0
      objectName: handle_head_primitives
      objectScaleNoiseMultiplierRange:
      - 0.9
      - 1.1
      objectStartPose: null
      objectStateDelayMax: 10
      objectStateRotationNoiseDegrees: 5.0
      objectStateXyzNoiseStd: 0.01
      obsDelayMax: 3
      obsList:
      - joint_pos
      - joint_vel
      - prev_action_targets
      - palm_pos
      - palm_rot
      - object_rot
      - fingertip_pos_rel_palm
      - keypoints_rel_palm
      - keypoints_rel_goal
      - object_scales
      observationType: full_state
      privilegedActions: false
      privilegedActionsTorque: 0.02
      randomizeObjectRotation: true
      reachGoalBonus: 1000.0
      record_data: false
      record_data_num_steps: 1000
      resetDofPosRandomIntervalArm: 0.1
      resetDofPosRandomIntervalFingers: 0.1
      resetDofVelRandomInterval: 0.5
      resetPositionNoiseX: 0.1
      resetPositionNoiseY: 0.1
      resetPositionNoiseZ: 0.02
      resetWhenDropped: false
      robotFriction: 0.5
      sanity_check_controls: false
      saveStates: false
      saveStatesFile: rootTensorsDofStates.bin
      startArmHigher: false
      stateList:
      - joint_pos
      - joint_vel
      - prev_action_targets
      - palm_pos
      - palm_rot
      - palm_vel
      - object_rot
      - object_vel
      - fingertip_pos_rel_palm
      - keypoints_rel_palm
      - keypoints_rel_goal
      - object_scales
      - closest_keypoint_max_dist
      - closest_fingertip_dist
      - lifted_object
      - progress
      - successes
      - reward
      stiffnessScale: 1.0
      successSteps: 10
      successTolerance: 0.075
      tableFriction: 0.5
      tableObjectZOffset: 0.25
      tableResetZ: 0.38
      tableResetZRange: 0.01
      targetSuccessTolerance: 0.01
      targetVolumeMaxs:
      - 0.35
      - 0.2
      - 0.95
      targetVolumeMins:
      - -0.35
      - -0.2
      - 0.6
      targetVolumeRegionScale: 1.0
      timeToUpdateTylerCurriculum: 5
      toleranceCurriculumIncrement: 0.9
      toleranceCurriculumInterval: 3000
      torqueDecay: 0.0
      torqueDecayInterval: 0.08
      torqueOnlyWhenLifted: true
      torqueProbRange:
      - 0.001
      - 0.1
      torqueScale: 2.0
      turn_off_extra_obs: false
      turn_off_extra_obs_slowly: false
      turn_off_object_vel_obs: false
      turn_off_object_vel_obs_slowly: false
      turn_off_palm_vel_obs: false
      turn_off_palm_vel_obs_slowly: false
      updateStepSizeTylerCurriculum: 0.01
      useActionDelay: true
      useFixedGoalStates: false
      useFixedInitObjectPose: false
      useObjectStateDelayNoise: false
      useObsDelay: true
      useRelativeControl: false
      use_green_robot: true
      use_hack_object_pos_offset: false
      use_obs_dropout: false
      withTableForceSensor: false
    name: SimToolReal
    physics_engine: physx
    sim:
      dt: 0.016666666666666666
      gravity:
      - 0.0
      - 0.0
      - -9.81
      num_client_threads: 8
      physx:
        bounce_threshold_velocity: 0.2
        contact_collection: 0
        contact_offset: 0.002
        default_buffer_size_multiplier: 25.0
        max_depenetration_velocity: 1000.0
        max_gpu_contact_pairs: 8388608
        num_position_iterations: 8
        num_subscenes: 4
        num_threads: 6
        num_velocity_iterations: 0
        rest_offset: 0.0
        solver_type: 1
      substeps: 2
      up_axis: z
      use_gpu_pipeline: true
    task:
      randomization_params:
        actions:
          distribution: gaussian
          operation: additive
          range:
          - 0.0
          - 0.01
          range_correlated:
          - 0.0
          - 0.01
          schedule: linear
          schedule_steps: 5000
        actor_params:
          object:
            rigid_body_properties:
              mass:
                distribution: uniform
                operation: scaling
                range:
                - 0.7
                - 1.3
                setup_only: true
            rigid_shape_properties:
              friction:
                distribution: uniform
                num_buckets: 100
                operation: scaling
                range:
                - 0.7
                - 1.3
              restitution:
                distribution: uniform
                num_buckets: 100
                operation: additive
                range:
                - 0.0
                - 0.3
          robot:
            color: true
            dof_properties:
              armature:
                distribution: uniform
                operation: scaling
                range:
                - 0.7
                - 1.3
              damping:
                distribution: loguniform
                operation: scaling
                range:
                - 0.7
                - 1.3
              effort:
                distribution: uniform
                operation: scaling
                range:
                - 0.7
                - 1.3
              friction:
                distribution: uniform
                operation: scaling
                range:
                - 0.7
                - 1.3
              stiffness:
                distribution: loguniform
                operation: scaling
                range:
                - 0.7
                - 1.3
            rigid_body_properties:
              mass:
                distribution: uniform
                operation: scaling
                range:
                - 0.7
                - 1.3
                setup_only: true
            rigid_shape_properties:
              friction:
                distribution: uniform
                num_buckets: 100
                operation: scaling
                range:
                - 0.7
                - 1.3
              restitution:
                distribution: uniform
                num_buckets: 100
                operation: additive
                range:
                - 0.0
                - 0.3
        frequency: 720
        observations:
          distribution: gaussian
          operation: additive
          range:
          - 0
          - 0.01
          range_correlated:
          - 0
          - 0.01
          schedule: constant
          schedule_steps: 5000
        sim_params:
          gravity:
            distribution: gaussian
            operation: additive
            range:
            - 0
            - 0.3
      randomize: false
task_name:
  desc: null
  value: SimToolReal
test:
  desc: null
  value: false
torch_deterministic:
  desc: null
  value: false
train:
  desc: null
  value:
    params:
      algo:
        name: a2c_continuous
      config:
        bounds_loss_coef: 0.0001
        central_value_config:
          clip_value: true
          kl_threshold: 0.016
          learning_rate: 0.0001
          mini_epochs: 2
          minibatch_size: 49152
          network:
            central_value: true
            mlp:
              activation: elu
              d2rl: false
              initializer:
                name: default
              regularizer:
                name: None
              units:
              - 1024
              - 1024
              - 512
              - 512
            name: actor_critic
          normalize_input: true
          truncate_grads: true
        clip_value: true
        critic_coef: 4.0
        defer_summaries_sec: 240
        depth_encoder_lr: 1.0e-05
        depth_encoder_type: scratch_cnn
        depth_feature_dim: 512
        depth_image_height: 64
        depth_image_width: 64
        device_name: cuda:0
        e_clip: 0.1
        entropy_coef: 0.0
        env_name: rlgpu
        expl_coef_block_size: 64
        expl_reward_coef: 0.0
        expl_reward_coef_embd_size: 32
        expl_reward_coef_scale: 0.005
        expl_reward_type: entropy
        expl_type: mixed_expl_learn_param
        freeze_depth_encoder: false
        gamma: 0.99
        good_reset_boundary: 0
        grad_norm: 1.0
        horizon_length: 16
        kl_threshold: 0.016
        learning_rate: 0.0001
        lr_schedule: adaptive
        max_epochs: 5
        max_frames: 100000000000000
        mini_epochs: 2
        minibatch_size: 512
        mixed_precision: true
        multi_gpu: true
        name: 00_depth_2gpu_test
        normalize_advantage: true
        normalize_input: true
        normalize_value: true
        num_actors: 512
        off_policy_ratio: 1.0
        player:
          deterministic: false
          games_num: 100000
          print_stats: false
        ppo: true
        print_stats: true
        reward_shaper:
          scale_value: 0.01
        save_best_after: 100
        save_frequency: 3000
        schedule_type: standard
        score_to_win: 1000000
        seq_length: 16
        summaries_interval_sec_max: 300
        summaries_interval_sec_min: 60
        tau: 0.95
        truncate_grads: true
        unfreeze_depth_after_epochs: -1
        use_depth_camera: true
        use_others_experience: lf
      load_checkpoint: false
      load_path: ''
      model:
        name: continuous_a2c_logstd
      network:
        mlp:
          activation: elu
          d2rl: false
          initializer:
            name: default
          regularizer:
            name: None
          units:
          - 1024
          - 1024
          - 512
          - 512
        name: actor_critic
        rnn:
          before_mlp: true
          layer_norm: true
          layers: 1
          name: lstm
          units: 1024
        separate: false
        space:
          continuous:
            fixed_sigma: coef_cond
            mu_activation: None
            mu_init:
              name: default
            sigma_activation: None
            sigma_init:
              name: const_initializer
              val: 0
      seed: 0
use_rl:
  desc: null
  value: true
wandb_activate:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: samratsahoo-stanford-university
wandb_group:
  desc: null
  value: depth_test
wandb_logcode_dir:
  desc: null
  value: ''
wandb_name:
  desc: null
  value: 00_depth_2gpu_test
wandb_project:
  desc: null
  value: simpretrain
wandb_tags:
  desc: null
  value: []
