"""Register fabrica Problem entries.

For each (insertion_part, receiver) pair in an assembly's
``inserts_into`` map, register a Problem from first principles:

  * ``receptive_urdf`` = a generated wrapper URDF that includes every
    fixture part's **assembled-frame mesh** (``<pid>.obj``) under an empty
    ``root`` link, with **identity joint origins**. The mesh vertices are
    already at A-frame coordinates, so no extra transform is needed.
    The URDF root therefore coincides with the assembly's A-frame origin
    (where scene-generation pinned the lowest fixture point to z=0).
  * ``insert_pose_rel_receptive`` = the ordered insertion-subgoal sequence.
    Plain insertion tasks use pre-insert, then the inserter's assembled pose
    in the A frame, ``(original_centroid_ins, inverse(q_a→c_ins))``.
  * ``hole_z_offset = 0``: the URDF root sits on the table top by
    construction.

Initial scope: all beam_2x insertions.
"""

import json
import logging
from pathlib import Path
from typing import Tuple

from scipy.spatial.transform import Rotation as R

from dextoolbench.objects import NAME_TO_OBJECT
from peg_in_hole_dynamic import (
    PROBLEM_REGISTRY,
    Problem,
    make_pre_insert_sequence,
    make_transport_pre_insert_sequence,
)
from peg_in_hole_dynamic.fabrica._pose_utils import write_fixture_urdf

_LOG = logging.getLogger(__name__)
_REPO_ROOT = Path(__file__).resolve().parents[2]
_FABRICA_DIR = _REPO_ROOT / "assets" / "urdf" / "fabrica"

_IDENTITY_POSE: Tuple[float, float, float, float, float, float, float] = (
    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
)


def _assembled_pose(transforms: dict, part_id: str
                    ) -> Tuple[float, float, float, float, float, float, float]:
    """Pose of ``part_id`` in the A frame, expressed as
    ``(x, y, z, qx, qy, qz, qw)`` — translation = original_centroid,
    rotation = inverse(q_a→c). When applied to the canonical mesh this
    reproduces the part's assembled position+orientation."""
    cx, cy, cz = transforms[part_id]["original_centroid"]
    qw, qx, qy, qz = transforms[part_id]["assembled_to_canonical_wxyz"]
    rot_xyzw = R.from_quat([qx, qy, qz, qw]).inv().as_quat()
    return (
        float(cx), float(cy), float(cz),
        float(rot_xyzw[0]), float(rot_xyzw[1]), float(rot_xyzw[2]), float(rot_xyzw[3]),
    )


def _register_assembly_problems(
    assembly: str,
    pre_insert_offset: float = 0.025,
    dense_traj_transport_offset: float = 0.10,
    dense_traj_prelude_lift_offset: float = 0.20,
) -> None:
    transforms_path = _FABRICA_DIR / assembly / "canonical_transforms.json"
    order_path = _FABRICA_DIR / assembly / "assembly_order.json"
    if not transforms_path.is_file() or not order_path.is_file():
        _LOG.info(
            "fabrica.%s: missing canonical_transforms.json or assembly_order.json — skipping",
            assembly,
        )
        return

    transforms = json.loads(transforms_path.read_text())
    order = json.loads(order_path.read_text())
    inserts_into = order.get("inserts_into", {})
    steps = order.get("steps", [])
    if not inserts_into or not steps:
        return

    for inserter_id, receiver_id in inserts_into.items():
        if inserter_id not in steps:
            _LOG.warning(
                "fabrica.%s.part_%s: %r not in assembly_order.steps — skipping",
                assembly, inserter_id, inserter_id,
            )
            continue
        if inserter_id not in transforms or receiver_id not in transforms:
            _LOG.warning(
                "fabrica.%s.part_%s: missing canonical_transforms entry — skipping",
                assembly, inserter_id,
            )
            continue

        # Fixture = every part already placed in the assembly before the
        # inserter step.
        fixture_pids = steps[: steps.index(inserter_id)]
        if not fixture_pids:
            _LOG.warning(
                "fabrica.%s.part_%s: empty fixture (no earlier steps) — skipping",
                assembly, inserter_id,
            )
            continue

        # The receptive URDF for each beam_2x problem is pre-generated by
        # peg_in_hole_dynamic.fabrica.beam_2x_problem_setup.step1_generate_assets:
        # fine CoACD hulls only for receiver geometry near the inserter
        # (the "hole walls"), with a coarse 4-box frame for the receiver
        # bulk plus a single A-frame bbox per non-receiver fixture part.
        # Other fabrica assemblies still use the older fully-CoACD'd URDFs
        # written below via write_fixture_urdf.
        fixtures_dir = _FABRICA_DIR / assembly / "insertion_fixtures"
        out_urdf_path = fixtures_dir / f"part_{inserter_id}.urdf"
        if out_urdf_path.is_file():
            receptive_rel = out_urdf_path.relative_to(_REPO_ROOT / "assets").as_posix()
        else:
            # Fallback: regenerate with the old "every-part-fully-CoACD'd" layout.
            fixture_entries = []
            skip_problem = False
            for pid in fixture_pids:
                coacd_dir = _FABRICA_DIR / assembly / pid / "coacd"
                decomp_files = sorted(coacd_dir.glob("decomp_*.obj"))
                if not decomp_files:
                    _LOG.warning(
                        "fabrica.%s.part_%s: no CoACD hulls in %s — skipping",
                        assembly, inserter_id, coacd_dir,
                    )
                    skip_problem = True
                    break
                mesh_rels = [f"../{pid}/coacd/{p.name}" for p in decomp_files]
                fixture_entries.append((pid, _assembled_pose(transforms, pid), mesh_rels))
            if skip_problem:
                continue
            fixture_urdf = write_fixture_urdf(
                output_path=out_urdf_path,
                parts=fixture_entries,
                robot_name=f"fixture_{assembly}_part_{inserter_id}",
            )
            receptive_rel = fixture_urdf.relative_to(_REPO_ROOT / "assets").as_posix()

        # Inserter pose in A frame.
        pose_ins = _assembled_pose(transforms, inserter_id)

        name = f"fabrica.{assembly}.part_{inserter_id}"
        PROBLEM_REGISTRY[name] = Problem(
            name=name,
            insertion_object_name=f"{assembly}_{inserter_id}_coacd",
            receptive_urdf=receptive_rel,
            insert_pose_rel_receptive=make_pre_insert_sequence(
                pose_ins, pre_insert_offset=pre_insert_offset
            ),
            hole_z_offset=0.0,
            pre_insert_offset=pre_insert_offset,
        )

        # Optional hybrid sibling — registered only when both the receiver
        # hybrid URDF and the inserter Object are present (generated by
        # step2_generate_sdf_hybrid.py). Same pose / hole_z_offset / pre-
        # insert_offset as the baseline, just different geometry.
        hybrid_recv = fixtures_dir / f"part_{inserter_id}_sdf_hybrid.urdf"
        hybrid_obj_key = f"{assembly}_{inserter_id}_sdf_hybrid"
        if hybrid_recv.is_file() and hybrid_obj_key in NAME_TO_OBJECT:
            hybrid_name = f"{name}_sdf_hybrid"
            PROBLEM_REGISTRY[hybrid_name] = Problem(
                name=hybrid_name,
                insertion_object_name=hybrid_obj_key,
                receptive_urdf=hybrid_recv.relative_to(_REPO_ROOT / "assets").as_posix(),
                insert_pose_rel_receptive=make_pre_insert_sequence(
                    pose_ins, pre_insert_offset=pre_insert_offset
                ),
                hole_z_offset=0.0,
                pre_insert_offset=pre_insert_offset,
            )

        # Matched-mass sibling — same receptive URDF as the baseline (the
        # fixture's per-part masses don't matter dynamically), only the
        # inserter object is swapped to its `_matchedmass_coacd` variant so
        # the grasped part carries measured mass + mesh-derived inertia.
        matched_obj_key = f"{assembly}_{inserter_id}_matchedmass_coacd"
        if matched_obj_key in NAME_TO_OBJECT:
            matched_name = f"{name}_matchedmass"
            PROBLEM_REGISTRY[matched_name] = Problem(
                name=matched_name,
                insertion_object_name=matched_obj_key,
                receptive_urdf=receptive_rel,
                insert_pose_rel_receptive=make_pre_insert_sequence(
                    pose_ins, pre_insert_offset=pre_insert_offset
                ),
                hole_z_offset=0.0,
                pre_insert_offset=pre_insert_offset,
            )

        # Matched-mass × SDF-hybrid sibling: SDF-hybrid receptive URDF +
        # matched-mass inserter. Only registered when both pieces exist.
        matched_sdfh_key = f"{assembly}_{inserter_id}_matchedmass_sdf_hybrid"
        if hybrid_recv.is_file() and matched_sdfh_key in NAME_TO_OBJECT:
            matched_sdfh_name = f"{name}_matchedmass_sdf_hybrid"
            hybrid_recv_rel = hybrid_recv.relative_to(_REPO_ROOT / "assets").as_posix()
            PROBLEM_REGISTRY[matched_sdfh_name] = Problem(
                name=matched_sdfh_name,
                insertion_object_name=matched_sdfh_key,
                receptive_urdf=hybrid_recv_rel,
                insert_pose_rel_receptive=make_pre_insert_sequence(
                    pose_ins, pre_insert_offset=pre_insert_offset
                ),
                hole_z_offset=0.0,
                pre_insert_offset=pre_insert_offset,
            )
            # dense_traj sibling: 3 hole-frame waypoints (transport_above,
            # pre_insert, final) paired at problem-config time with a per-
            # episode prelude (lift-in-place + over-hole) that the env
            # constructs at reset.
            dense_traj_name = f"{matched_sdfh_name}_dense_traj"
            PROBLEM_REGISTRY[dense_traj_name] = Problem(
                name=dense_traj_name,
                insertion_object_name=matched_sdfh_key,
                receptive_urdf=hybrid_recv_rel,
                insert_pose_rel_receptive=make_transport_pre_insert_sequence(
                    pose_ins,
                    pre_insert_offset=pre_insert_offset,
                    transport_offset=dense_traj_transport_offset,
                ),
                hole_z_offset=0.0,
                pre_insert_offset=pre_insert_offset,
                prelude_lift_offset=dense_traj_prelude_lift_offset,
            )


_register_assembly_problems("beam_2x")
# beam_3x pillars / caps are 1.5x larger than beam_2x's, so the tip SDF
# (TIP_HEIGHT_M in beam_3x_problem_setup) and the pre-insert clearance both
# scale by 1.5x: 0.025 m -> 0.0375 m. dense_traj transport + prelude lift
# also scale up so the policy gets a meaningfully tall lift on the larger
# part.
_register_assembly_problems(
    "beam_3x",
    pre_insert_offset=0.0375,
    dense_traj_transport_offset=0.15,
    dense_traj_prelude_lift_offset=0.25,
)
