#!/usr/bin/env python3
"""Generate diverse initial-state scenes for a fabrica assembly.

For each scene, samples a (start_pose, trajectory) pair for every part such
that:

- Start poses are drawn from each part's discrete set of stable resting
  orientations (precomputed by ``compute_stable_rests.py``) plus a uniform
  random yaw and a uniform random (x, y) on the table.
- Sampled placements are rejection-checked against the table edges and
  against the world poses of any parts that come earlier in
  ``assembly_order.json`` (those parts are already in the fixture when this
  part is being manipulated).
- Per-part trajectories are generated by
  ``fabrica.scene_generation.trajectory_generation.generate_variable_trajectory``
  with ~2.5 cm spacing between consecutive waypoints. The lift altitude is
  raised iteratively if any lift+transit waypoint comes within 5 cm of any
  placed part.

Output: ``assets/urdf/fabrica/{assembly}/scenes.npz`` with arrays
  - ``start_poses``  : float32 [num_scenes, num_parts, 7] (xyz + xyzw quat)
  - ``goals``        : float32 [num_scenes, num_parts, max_traj_len, 7]
                       (zero-padded past the per-(scene, part) length)
  - ``traj_lengths`` : int32   [num_scenes, num_parts]

Usage:
    python fabrica/scene_generation/generate_scenes.py --assembly beam
    python fabrica/scene_generation/generate_scenes.py --assembly beam \\
        --num-scenes 10 --seed 0 --force
"""

import argparse
import sys
from pathlib import Path

import numpy as np
import trimesh
from scipy.spatial.transform import Rotation as R

from fabrica.benchmark_processing.step3_generate_trajectories import (
    compute_table_offset,
    load_assembly_config,
    quat_inverse_wxyz,
)
from fabrica.scene_generation.trajectory_generation import generate_variable_trajectory

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
ASSETS_DIR = REPO_ROOT / "assets" / "urdf" / "fabrica"

# --- Scene constants (world frame) ---

TABLE_TOP_Z = 0.53          # world z of the table top surface
TABLE_HALF_X = 0.2375       # half of the 0.475 m table extent in x
TABLE_HALF_Y = 0.2          # half of the 0.4 m table extent in y
EDGE_INSET = 0.05           # safety margin from table edges (m)

# Trajectory generation
TARGET_SPACING = 0.025      # ~2.5 cm between consecutive waypoints
LIFT_INITIAL = TABLE_TOP_Z + 0.20   # initial lift altitude (m)
LIFT_INCREMENT = 0.05       # raise lift altitude by this much per retry (m)
MAX_LIFT_ITERATIONS = 5     # how many times to raise lift before giving up

# Collision-check
PROXIMITY_MARGIN = 0.05     # min allowed distance between active and placed (m)
START_PROXIMITY_MARGIN = 0.01  # min distance between start poses within a scene (m)

# Placement retry budget
MAX_PLACEMENT_RETRIES = 200


# --- Quaternion / pose helpers ---

def _wxyz_to_xyzw(q_wxyz):
    return [q_wxyz[1], q_wxyz[2], q_wxyz[3], q_wxyz[0]]


def _matrix_to_wxyz(R_mat):
    rot = R.from_matrix(R_mat)
    xyzw = rot.as_quat()
    return [float(xyzw[3]), float(xyzw[0]), float(xyzw[1]), float(xyzw[2])]


def _wxyz_to_matrix(q_wxyz):
    rot = R.from_quat([q_wxyz[1], q_wxyz[2], q_wxyz[3], q_wxyz[0]])
    return rot.as_matrix()


def make_transform(pos, quat_wxyz):
    """Build a 4x4 homogeneous transform from world (pos, quat_wxyz)."""
    T = np.eye(4)
    T[:3, :3] = _wxyz_to_matrix(quat_wxyz)
    T[:3, 3] = pos
    return T


def transform_mesh(mesh, pos, quat_wxyz):
    """Return a copy of `mesh` transformed by world pose (pos, quat_wxyz)."""
    out = mesh.copy()
    out.apply_transform(make_transform(pos, quat_wxyz))
    return out


def compose_link_pose(stable_rest_T, yaw_rad, x, y):
    """Compose URDF link pose for an active part on the table.

    The stable rest 4x4 places the canonical mesh on z=0 in a stable
    orientation. Then yaw rotates about world z, then (x, y) translates
    in the table plane and TABLE_TOP_Z lifts the bottom onto the surface.

    Returns (p_link [3], quat_wxyz [4]).
    """
    R_rest = stable_rest_T[:3, :3]
    t_rest = stable_rest_T[:3, 3]

    R_yaw = R.from_euler("z", yaw_rad).as_matrix()

    R_link = R_yaw @ R_rest
    p_link = R_yaw @ t_rest + np.array([x, y, TABLE_TOP_Z])

    return p_link, _matrix_to_wxyz(R_link)


def world_assembled_pose(transforms_pid, table_offset):
    """World (pos, quat_wxyz) for a part in its final fixture pose."""
    centroid = np.array(transforms_pid["original_centroid"])
    pos = centroid + table_offset
    a2c = transforms_pid["assembled_to_canonical_wxyz"]
    quat_wxyz = quat_inverse_wxyz(a2c)
    return pos, quat_wxyz


# --- Collision checks ---
#
# We use two CollisionManagers per part-placement:
#   - placed_cm: holds the previously-placed parts at their world fixture
#                poses. Built once per part. Note that placed parts may
#                overlap each other in the fixture (they're inserted into
#                each other), so we MUST NOT call min_distance_internal on
#                this manager — that would be dominated by intra-fixture
#                overlap.
#   - active_cm: holds the active part's canonical mesh at identity. We
#                update its transform per query via set_transform("active", T).
#
# Distance is queried via active_cm.min_distance_other(placed_cm), which
# returns the closest distance between any active vertex and any placed
# vertex — exactly what we want.

def make_placed_cm(placed_meshes_world):
    cm = trimesh.collision.CollisionManager()
    for name, m in placed_meshes_world.items():
        cm.add_object(name, m)
    return cm


def make_active_cm(canonical_mesh):
    cm = trimesh.collision.CollisionManager()
    cm.add_object("active", canonical_mesh)
    return cm


def update_active(active_cm, pos, quat_wxyz):
    active_cm.set_transform("active", make_transform(pos, quat_wxyz))


def active_to_placed_distance(active_cm, placed_cm):
    return float(active_cm.min_distance_other(placed_cm))


def lift_transit_clear(active_cm, placed_cm, waypoints, lift_transit_end):
    """Walk lift+transit waypoints; True iff every one is >= PROXIMITY_MARGIN
    from any placed part."""
    for i in range(lift_transit_end):
        pos = waypoints[i, :3]
        qx, qy, qz, qw = waypoints[i, 3:7]
        # waypoints are stored in xyzw; convert to wxyz for the transform
        update_active(active_cm, pos, [qw, qx, qy, qz])
        if active_to_placed_distance(active_cm, placed_cm) < PROXIMITY_MARGIN:
            return False
    return True


# --- Per-part placement ---

def sample_part_placement(
    rng,
    pid,
    canonical_mesh,
    stable_rests_for_pid,
    placed_meshes_world,
    prev_start_meshes_world,
    fixture_pose,
    insertion_dir,
):
    """Sample a (start_pose, trajectory) for a single part.

    Tries up to MAX_PLACEMENT_RETRIES (x, y, yaw, stable_rest) draws and
    iterates lift altitude internally. Returns (start_pos, start_quat_wxyz,
    waypoints, lift_transit_end) on success, or None if no valid placement
    is found.

    Two collision sets are checked:
      - ``placed_meshes_world``: previously-placed parts at their world
        fixture poses. The active part's lift+transit waypoints must clear
        these (so the trajectory doesn't crash into the assembled stack).
      - ``prev_start_meshes_world``: previously-sampled parts in *this same
        scene* at their start poses on the table. The active part's start
        pose must not overlap any of these so the cached scene is a
        physically realizable table state.
    """
    n_rests = len(stable_rests_for_pid)
    end_pos, end_quat_wxyz = fixture_pose

    # Reusable collision managers — both obstacle sets are static in the
    # world frame for the duration of this call; the active mesh is
    # registered at identity and updated via set_transform per query.
    has_placed = bool(placed_meshes_world)
    placed_cm = make_placed_cm(placed_meshes_world) if has_placed else None
    has_prev_starts = bool(prev_start_meshes_world)
    prev_starts_cm = (
        make_placed_cm(prev_start_meshes_world) if has_prev_starts else None
    )
    active_cm = make_active_cm(canonical_mesh)

    n_bbox_fail = 0
    n_start_fail = 0
    n_traj_fail = 0

    for attempt in range(MAX_PLACEMENT_RETRIES):
        stable_idx = int(rng.integers(n_rests))
        stable_T = stable_rests_for_pid[stable_idx]
        yaw = float(rng.uniform(-np.pi, np.pi))
        x = float(rng.uniform(-(TABLE_HALF_X - EDGE_INSET), TABLE_HALF_X - EDGE_INSET))
        y = float(rng.uniform(-(TABLE_HALF_Y - EDGE_INSET), TABLE_HALF_Y - EDGE_INSET))

        start_pos, start_quat_wxyz = compose_link_pose(stable_T, yaw, x, y)

        # 1. Rotated bbox stays inside the table (with edge inset).
        active_mesh_world = transform_mesh(canonical_mesh, start_pos, start_quat_wxyz)
        bb_min, bb_max = active_mesh_world.bounds
        if (
            bb_min[0] < -(TABLE_HALF_X - EDGE_INSET)
            or bb_max[0] > (TABLE_HALF_X - EDGE_INSET)
            or bb_min[1] < -(TABLE_HALF_Y - EDGE_INSET)
            or bb_max[1] > (TABLE_HALF_Y - EDGE_INSET)
        ):
            n_bbox_fail += 1
            continue

        # 2. Start pose must not overlap any previously-sampled start in
        #    the same scene (so the snapshot of all starts on the table is
        #    a physically valid configuration).
        if has_prev_starts:
            update_active(active_cm, start_pos, start_quat_wxyz)
            if active_to_placed_distance(active_cm, prev_starts_cm) < START_PROXIMITY_MARGIN:
                n_start_fail += 1
                continue

        # 3. Try to find a collision-free trajectory by raising lift altitude.
        # The lift+transit check is the authoritative collision filter; it
        # subsumes a "start is in collision with fixture" check (the first
        # lift waypoint is essentially the start pose).
        chosen_waypoints = None
        chosen_end = None
        for lift_iter in range(MAX_LIFT_ITERATIONS):
            clearance_z = LIFT_INITIAL + lift_iter * LIFT_INCREMENT
            waypoints, lift_transit_end = generate_variable_trajectory(
                start_pos,
                start_quat_wxyz,
                end_pos,
                end_quat_wxyz,
                clearance_z=clearance_z,
                insertion_dir=insertion_dir,
                target_spacing=TARGET_SPACING,
            )
            if not has_placed or lift_transit_clear(
                active_cm, placed_cm, waypoints, lift_transit_end
            ):
                chosen_waypoints = waypoints
                chosen_end = lift_transit_end
                break

        if chosen_waypoints is None:
            n_traj_fail += 1
            continue  # try a different (x, y, yaw, rest)

        return start_pos, start_quat_wxyz, chosen_waypoints, chosen_end

    print(
        f"  [debug] part {pid} after {MAX_PLACEMENT_RETRIES} attempts: "
        f"bbox_fail={n_bbox_fail}, start_fail={n_start_fail}, "
        f"traj_fail={n_traj_fail}",
        flush=True,
    )
    return None


# --- Scene generation ---

def generate_scenes(assembly, num_scenes, seed):
    rng = np.random.default_rng(seed)

    transforms, order_config = load_assembly_config(assembly)
    assembly_order = order_config["steps"]
    insertion_directions = order_config.get("insertion_directions", {})
    table_offset = compute_table_offset(assembly, transforms)

    # Load canonical meshes (used as collision proxies, since they're the
    # same OBJs Isaac Gym actually loads).
    canonical_meshes = {}
    for pid in assembly_order:
        mesh_path = ASSETS_DIR / assembly / pid / f"{pid}_canonical.obj"
        canonical_meshes[pid] = trimesh.load_mesh(str(mesh_path), process=False)

    # Load stable rests
    stable_rests = {}
    for pid in assembly_order:
        rests_path = ASSETS_DIR / assembly / "stable_rests" / f"{pid}.npz"
        if not rests_path.exists():
            raise FileNotFoundError(
                f"Missing stable rests for part {pid}: {rests_path}\n"
                f"Run compute_stable_rests.py --assembly {assembly} first."
            )
        data = np.load(rests_path)
        stable_rests[pid] = data["transforms"]

    # World fixture poses (per part) — these are the trajectory end poses
    # and also the poses at which already-placed parts sit during scene
    # generation for later parts in the assembly order.
    fixture_poses = {
        pid: world_assembled_pose(transforms[pid], table_offset) for pid in assembly_order
    }

    num_parts = len(assembly_order)
    print(f"Assembly: {assembly}")
    print(f"Parts: {assembly_order}")
    print(f"Table offset: {table_offset}")
    print(f"Generating {num_scenes} scenes (seed={seed})...\n")

    all_starts_xyzw = []  # list per scene → [num_parts, 7] xyzw
    all_goals_per_scene = []  # list per scene → list per part → [traj_len, 7] xyzw
    all_lengths = []      # list per scene → [num_parts]

    for scene_idx in range(num_scenes):
        starts_for_scene = np.zeros((num_parts, 7), dtype=np.float32)
        goals_for_scene = []
        lengths_for_scene = np.zeros(num_parts, dtype=np.int32)

        # Accumulates the world meshes of parts already placed at their
        # sampled start poses *in this scene*. New parts must not overlap
        # any of these so the snapshot of all 5 starts on the table is a
        # valid physical configuration.
        prev_start_meshes = {}

        for p_idx, pid in enumerate(assembly_order):
            placed_meshes = {
                f"placed_{prev_pid}": transform_mesh(
                    canonical_meshes[prev_pid], *fixture_poses[prev_pid]
                )
                for prev_pid in assembly_order[:p_idx]
            }

            result = sample_part_placement(
                rng,
                pid,
                canonical_meshes[pid],
                stable_rests[pid],
                placed_meshes,
                prev_start_meshes,
                fixture_poses[pid],
                insertion_directions.get(pid),
            )
            if result is None:
                raise RuntimeError(
                    f"Scene {scene_idx}: failed to place part {pid} after "
                    f"{MAX_PLACEMENT_RETRIES} attempts. Try a different seed "
                    f"or relax workspace constraints."
                )
            start_pos, start_quat_wxyz, waypoints, lift_transit_end = result

            starts_for_scene[p_idx, 0:3] = start_pos
            starts_for_scene[p_idx, 3:7] = _wxyz_to_xyzw(start_quat_wxyz)
            goals_for_scene.append(waypoints)
            lengths_for_scene[p_idx] = len(waypoints)

            prev_start_meshes[f"start_{pid}"] = transform_mesh(
                canonical_meshes[pid], start_pos, start_quat_wxyz
            )

            print(
                f"  scene {scene_idx} part {pid}: "
                f"start=({start_pos[0]:+.3f}, {start_pos[1]:+.3f}, {start_pos[2]:+.3f}) "
                f"len={len(waypoints)} lift_transit={lift_transit_end}",
                flush=True,
            )

        all_starts_xyzw.append(starts_for_scene)
        all_goals_per_scene.append(goals_for_scene)
        all_lengths.append(lengths_for_scene)

    # Pad goals to a uniform max length across all (scene, part)
    max_traj_len = max(
        max(len(g) for g in scene_goals) for scene_goals in all_goals_per_scene
    )
    padded_goals = np.zeros(
        (num_scenes, num_parts, max_traj_len, 7), dtype=np.float32
    )
    for s_idx, scene_goals in enumerate(all_goals_per_scene):
        for p_idx, traj in enumerate(scene_goals):
            padded_goals[s_idx, p_idx, : len(traj), :] = traj

    starts_array = np.stack(all_starts_xyzw, axis=0).astype(np.float32)
    lengths_array = np.stack(all_lengths, axis=0).astype(np.int32)

    return starts_array, padded_goals, lengths_array


def main():
    parser = argparse.ArgumentParser(
        description="Generate diverse initial-state scenes for a fabrica assembly.",
    )
    parser.add_argument("--assembly", type=str, required=True)
    parser.add_argument("--num-scenes", type=int, default=10)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--force", action="store_true",
                        help="Overwrite existing scenes.npz.")
    args = parser.parse_args()

    out_path = ASSETS_DIR / args.assembly / "scenes.npz"
    if out_path.exists() and not args.force:
        print(f"{out_path} exists. Use --force to overwrite.")
        return

    starts, goals, lengths = generate_scenes(
        args.assembly, args.num_scenes, args.seed
    )

    np.savez(
        out_path,
        start_poses=starts,
        goals=goals,
        traj_lengths=lengths,
    )

    print(f"\nSaved {out_path.relative_to(REPO_ROOT)}")
    print(f"  start_poses : {starts.shape} {starts.dtype}")
    print(f"  goals       : {goals.shape} {goals.dtype}")
    print(f"  traj_lengths: {lengths.shape} {lengths.dtype}")
    print(f"  per-(scene,part) length min/max: {lengths.min()} / {lengths.max()}")


if __name__ == "__main__":
    main()
